version: '3.7'

services:

  fr:
    container_name: fr
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/task-manager-frontend'
      - '/task-manager-frontend/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
 
