export const tasksActionTypes = {
  REQ_GET_TASKS: 'REQ_GET_TASKS',
  REQ_GET_TASKS_SUCCESS: 'REQ_GET_TASKS_SUCCESS',
  REQ_GET_TASKS_FAILURE: 'REQ_GET_TASKS_FAILURE',
  SET_CURRENT_INPUT: 'SET_CURRENT_INPUT',
  REQ_ADD_TASK: 'REQ_ADD_TASK',
  REQ_ADD_TASK_SUCCESS: 'REQ_ADD_TASK_SUCCESS',
  REQ_ADD_TASK_FAILURE: 'REQ_ADD_TASK_FAILURE',

  REQ_DELETE_TASK: 'REQ_DELETE_TASK',
  REQ_DELETE_TASK_SUCCESS: 'REQ_DELETE_TASK_SUCCESS',
  REQ_DELETE_TASK_FAILURE: 'REQ_DELETE_TASK_FAILURE',

  REQ_TOGGLE_TASK_COMPLETION: 'REQ_TOGGLE_TASK_COMPLETION',
  REQ_TOGGLE_IS_COMPLETE_SUCCESS: 'REQ_TOGGLE_IS_COMPLETE_SUCCESS',
  REQ_TOGGLE_IS_COMPLETE_FAILURE: 'REQ_TOGGLE_IS_COMPLETE_FAILURE',

  REQ_SET_EDIT_MODE: 'REQ_SET_EDIT_MODE',
  REQ_SAVE_TASK_CHANGES_SUCCESS: 'REQ_SAVE_TASK_CHANGES_SUCCESS',
}
